Dev
beehexacorp/sql-account-cli pull request #1
Opened 2024-11-20 11:09 UTC by datnguyenbhx

start service with custom user + cloudflare tunnel connect

2024-11-21 10:06 UTC, beeGiaLe requested changes

2024-11-21 10:06 UTC, beeGiaLe commented on lib/login.js
> +      "http://localhost:5001/api/app/login",
sao lại fix cứng port là 5001 vậy? người ta có deploy bằng any port nha.

2024-11-21 12:57 UTC, beeGiaLe requested changes

2024-11-21 12:57 UTC, beeGiaLe commented on lib/deploy.js
> +        Constants.WriteJsonFile(Constants.CONFIGURATION_FILE_PATH, {'PORT':port,'APP_NAME':appName})
nên viết 1 lib nhỏ get config ra, rồi update, xong ghi vô lại, chứ như vầy nó sẽ ghi đè, nhỡ đâu sau này mình thêm config (API_VERSION, v...) thì gây ra bug nghiêm trọng.

2024-11-21 12:57 UTC, beeGiaLe commented on lib/login.js
> +      `http://localhost:${configurationData['PORT']}/api/app/login`,
chỗ này vẫn sai nhé, 

1. Nếu chạy bằng IIS, thì nó sẽ là http://localhost/${configurationData['APP_NAME']}/api/app/login
2. Nếu chạy bằng Windows Service nó mới là  `http://localhost:${configurationData['PORT']}/api/app/login`,

Như vậy, lúc install, rõ ràng là em cần thêm config { INSTALLATION_TYPE, APP_NAME, PORT }
Ngoài ra, 

1. Trong th người ta đã install = IIS rồi, thì phải xoá app, install sang Windows Service, và ngược lại, để đảm bảo là configurationData ko bị loạn
2. Người ta có thể cài 2 - n app (mỗi app khác nhau cái APP_NAME và port), nên configurationData nó phải là 1 list (phân biệt bởi APP_NAME), khi gọi login rõ ràng mình phải list danh sách đó lên cho người ta chọn họ muốn login với app nào. Trong trường hợp chỉ có 1 app thì khỏi list.

2024-11-22 09:10 UTC, datnguyenbhx commented on lib/deploy.js
> +        Constants.WriteJsonFile(Constants.CONFIGURATION_FILE_PATH, {'PORT':port,'APP_NAME':appName})
WriteJsonFile là hàm lấy dữ liệu ra và update JSON đó sau đó ghi lại vào file nên không phải là ghi đè lên ạ

2024-11-23 03:25 UTC, beeGiaLe requested changes

2024-11-23 03:25 UTC, beeGiaLe commented on data/constants.js
> +class Constants {
1. Làm javascript chịu khó bỏ bớt các phần liên quan đến OOP (mặc dù vẫn tư duy theo OOP)
2. Với cả, naming convention của javascript, thì function là camelCase, class là PascalCase.

```javascript
import fs from 'fs';

// không cần class based

export const CONFIGURATION_FILE_PATH = "data/configuration.json";
export const GITHUB_RELEASE_URL = "beehexacorp/sql-account-rest-api/releases/";

export function readJsonFile(filePath) {
  try {
    const data = fs.readFileSync(filePath, "utf8");
    return JSON.parse(data);
  } catch (err) {
    throw new Error("Error when reading file or parsing JSON: " + err);
  }
}

export function writeJsonFile(filePath, newData) {
  try {
    let jsonData = {};
    try {
      jsonData = readJsonFile(filePath);
    } catch (err) {
      // File may not exist or contain invalid JSON, so we proceed with empty object
    }
    jsonData = { ...jsonData, ...newData };
    const jsonString = JSON.stringify(jsonData, null, 2);
    fs.writeFileSync(filePath, jsonString);
    return "File written successfully.";
  } catch (err) {
    throw new Error("Error writing file: " + err);
  }
}
```

2024-11-27 10:24 UTC, beeGiaLe approved these changes

2024-11-27 10:24 UTC, merged