Fix System Path \ & /
beehexacorp/sql-account-cli pull request #5
Opened 2024-12-23 09:47 UTC by datnguyenbhx

2024-12-24 08:58 UTC, beeGiaLe requested changes

2024-12-24 08:58 UTC, beeGiaLe commented on data/configuration.json
> +  "API_VERSION": "release-0.0.25",
sao mấy cái này lại hardcode nhỉ?

2024-12-28 10:23 UTC, datnguyenbhx commented on data/configuration.json
> +  "API_VERSION": "release-0.0.25",
file này được tạo ra trong quá trình cài đặt package để lưu lại Configuration thực hiện update chứ không phải hardcode ạ

2025-01-06 02:01 UTC, beeGiaLe requested changes

2025-01-06 02:01 UTC, beeGiaLe commented on lib/deploy.js
> +async function configureWindowsStartup(exePath) {
File này bắt đầu phình to ra rồi, tách nó ra thành 3 file nhỏ: winfowsServiceDeployment.js, iisDeployment, windowsStartupDeployment

2025-01-06 03:07 UTC, beeGiaLe approved these changes

2025-01-06 03:07 UTC, merged